version: '3.1'

services:

  article-service:
    build: ./article-service
    environment:
      MICRO_REGISTRY: "mdns"

  # open-service:
  #   build: ./open-service
  #   environment:
  #     MICRO_REGISTRY: "mdns"
  #
  web-app:
    build: ./web-app
    ports:
      - 8080:8080

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database

  # datastore:
  #   image: mongo
  #   ports:
  #     - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
